'\" t
.\"     Title: timew-resize
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.13
.\"      Date: 2021-05-16
.\"    Manual: User Manuals
.\"    Source: timew 1.4.3
.\"  Language: English
.\"
.TH "TIMEW\-RESIZE" "1" "2021-05-16" "timew 1.4.3" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew-resize \- set interval duration
.SH "SYNOPSIS"
.sp
.nf
\fBtimew resize\fP \fI<id>\fP\fB...\fP \fI<duration>\fP
.fi
.br
.SH "DESCRIPTION"
.sp
The \(aqresize\(aq command is used to change the duration of a closed interval.
Using the \(aqsummary\(aq command, and specifying the \(aq:ids\(aq hint shows interval IDs.
Using the right ID, you can identify an interval to resize.
.SH "EXAMPLES"
.sp
For example, show the IDs:
.sp
.if n .RS 4
.nf
.fam C
$ timew summary :week :ids
.fam
.fi
.if n .RE
.sp
Then having selected \(aq@3\(aq as the interval you wish to resize:
.sp
.if n .RS 4
.nf
.fam C
$ timew resize @3 15mins
.fam
.fi
.if n .RE
.sp
Note that you can resize multiple intervals,:
.sp
.if n .RS 4
.nf
.fam C
$ timew resize @3 @1 @13 1hour
.fam
.fi
.if n .RE
.SH "SEE ALSO"
.sp
\fBtimew\-lengthen\fP(1),
\fBtimew\-modify\fP(1),
\fBtimew\-shorten\fP(1),
\fBtimew\-summary\fP(1),
\fBtimew\-tag\fP(1),
\fBtimew\-untag\fP(1)