'\" t
.\"     Title: timew-track
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2023-10-14
.\"    Manual: User Manuals
.\"    Source: timew 1.7.0
.\"  Language: English
.\"
.TH "TIMEW\-TRACK" "1" "2023-10-14" "timew 1.7.0" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew-track \- add intervals to the database
.SH "SYNOPSIS"
.sp
.nf
\fBtimew track\fP \fI<range>\fP [\fI<tag>\fP\fB...\fP]
.fi
.br
.SH "DESCRIPTION"
.sp
The track command is used to add tracked time in the past.
Perhaps you forgot to record time, or are just filling in old entries.
.SH "EXAMPLES"
.sp
For example:
.sp
.if n .RS 4
.nf
.fam C
$ timew track :yesterday \*(AqTraining Course\*(Aq
$ timew track 9am \- 11am \*(AqStaff Meeting\*(Aq
.fam
.fi
.if n .RE
.sp
Note that the track command expects a closed interval (start and end time), when recording.
If a closed interval is not provided, the \*(Aqtrack\*(Aq command behaves the same as the \*(Aqstart\*(Aq command.
.SH "SEE ALSO"
.sp
\fBtimew\-cancel\fP(1),
\fBtimew\-continue\fP(1),
\fBtimew\-start\fP(1),
\fBtimew\-stop\fP(1)