'\" t
.\"     Title: timew-annotate
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.13
.\"      Date: 2021-05-16
.\"    Manual: User Manuals
.\"    Source: timew 1.4.3
.\"  Language: English
.\"
.TH "TIMEW\-ANNOTATE" "1" "2021-05-16" "timew 1.4.3" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew-annotate \- add an annotation to intervals
.SH "SYNOPSIS"
.sp
.nf
\fBtimew annotate\fP [\fI<id>\fP\fB...\fP] \fI<annotation>\fP\fB...\fP
.fi
.br
.SH "DESCRIPTION"
.sp
The \(aqannotate\(aq command is used to add an annotation to an interval.
Using the \(aqsummary\(aq command, and specifying the \(aq:ids\(aq hint shows interval IDs.
Using the right ID, you can identify an interval to annotate.
.SH "EXAMPLES"
.sp
For example, show the IDs:
.sp
.if n .RS 4
.nf
.fam C
$ timew summary :week :ids
.fam
.fi
.if n .RE
.sp
Then having selected \(aq@2\(aq as the interval you wish to annotate:
.sp
.if n .RS 4
.nf
.fam C
$ timew annotate @2 \(aqLorem ipsum...\(aq
.fam
.fi
.if n .RE
.sp
Note that you can annotate multiple intervals with the same annotation:
.sp
.if n .RS 4
.nf
.fam C
$ timew annotate @2 @10 @23 \(aqLorem ipsum dolor sit amet...\(aq
.fam
.fi
.if n .RE
.sp
If there is active time tracking, you can omit the ID when you want to add annotations to the current open interval:
.sp
.if n .RS 4
.nf
.fam C
$ timew start foo
$ timew annotate bar
.fam
.fi
.if n .RE
.sp
This results in the current interval having annotations \(aqfoo\(aq and \(aqbar\(aq.
.SH "BUGS"
.sp
Currently the annotation command picks the last token from the command line and uses it as annotation.
I.e. using no quotes in an annotation command like
.sp
.if n .RS 4
.nf
.fam C
$ timew annotate @1 lorem ipsum dolor
.fam
.fi
.if n .RE
.sp
will result in interval @1 having only \(aqdolor\(aq as its annotation.
.SH "SEE ALSO"
.sp
\fBtimew\-tag\fP(1)