'\" t
.\"     Title: timew-summary
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.13
.\"      Date: 2021-05-16
.\"    Manual: User Manuals
.\"    Source: timew 1.4.3
.\"  Language: English
.\"
.TH "TIMEW\-SUMMARY" "1" "2021-05-16" "timew 1.4.3" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew-summary \- display a time\-tracking summary
.SH "SYNOPSIS"
.sp
.nf
\fBtimew summary\fP [\fI<range>\fP] [\fI<tag>\fP\fB...\fP]
.fi
.br
.SH "DESCRIPTION"
.sp
Displays a report summarizing tracked and untracked time for the current day by default.
Accepts date ranges and tags for filtering, or shortcut hints:
.sp
.if n .RS 4
.nf
.fam C
$ timew summary monday \- today
$ timew summary :week
$ timew summary :month
.fam
.fi
.if n .RE
.sp
The \(aq:ids\(aq hint adds an \(aqID\(aq column to the summary report output for interval modification.
.SH "CONFIGURATION"
.sp
\fBreports.summary.holidays\fP
.RS 4
Determines whether relevant holidays are shown beneath the report.
Default value is \(aqyes\(aq.
.RE
.SH "SEE ALSO"
.sp
\fBtimew\-day\fP(1),
\fBtimew\-lengthen\fP(1),
\fBtimew\-modify\fP(1),
\fBtimew\-month\fP(1),
\fBtimew\-shorten\fP(1),
\fBtimew\-tag\fP(1),
\fBtimew\-untag\fP(1),
\fBtimew\-week\fP(1)