'\" t
.\"     Title: timew-summary
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2023-12-30
.\"    Manual: User Manuals
.\"    Source: timew 1.7.0-dev
.\"  Language: English
.\"
.TH "TIMEW\-SUMMARY" "1" "2023-12-30" "timew 1.7.0\-dev" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew-summary \- display a time\-tracking summary
.SH "SYNOPSIS"
.sp
.nf
\fBtimew summary\fP [\fI<range>\fP] [\fI<tag>\fP\fB...\fP]
\fBtimew summary\fP [\fI<id>\fP\fB...\fP]
.fi
.br
.SH "DESCRIPTION"
.sp
Displays a table summarizing tracked time, by default for the current day.
Accepts date ranges (or range hints) and tags, or ids for filtering.
.sp
When ids are given, date ranges are ignored.
Specifying both, tags and ids, is an error.
.SH "HINTS"
.sp
Apart from range hints (see \fBtimew\-hints\fP(7)), the summary report adheres to the following hints:
.sp
\fB:annotations\fP, \fB:no\-annotations\fP
.RS 4
Toggle the display of annotations in the summary report.
Can be used on the command line to override the configured setting.
The \*(Aq:annotations\*(Aq hint adds an \*(AqAnnotation\*(Aq column to the summary table.
The annotation column is limited to 15 characters.
Longer values in this column are truncated to 12 characters and shown with an ellipsis attached.
.RE
.sp
\fB:holidays\fP, \fB:no\-holidays\fP
.RS 4
Toggle the display of holidays in the summary report.
Can be used on the command line to override the configured setting.
.RE
.sp
\fB:ids\fP, \fB:no\-ids\fP
.RS 4
Toggle the display of ids in the summary report.
Can be used on the command line to override the configured setting.
The \*(Aq:ids\*(Aq hint adds an \*(AqID\*(Aq column to the summary table.
Those ids can be used for interval modification.
.RE
.sp
\fB:tags\fP, \fB:no\-tags\fP
.RS 4
Toggle the display of tags in the summary report.
Can be used on the command line to override the configured setting.
The \*(Aq:tags\*(Aq hint adds a \*(AqTags\*(Aq column to the summary table.
.RE
.SH "CONFIGURATION"
.sp
\fBreports.summary.annotations\fP
.RS 4
Determines whether the annotation column is shown in the summary.
Can be overridden by the \*(Aq:annotations\*(Aq or \*(Aq:no\-annotations\*(Aq hint, respectively.
Default value is \*(Aqno\*(Aq
.RE
.sp
\fBreports.summary.holidays\fP
.RS 4
Determines whether relevant holidays are shown beneath the report.
Can be overridden by the \*(Aq:holidays\*(Aq or \*(Aq:no\-holidays\*(Aq hint, respectively.
Default value is \*(Aqyes\*(Aq.
.RE
.sp
\fBreports.summary.ids\fP
.RS 4
Determines whether the id column is shown in the summary.
Can be overridden by the \*(Aq:ids\*(Aq or \*(Aq:no\-ids\*(Aq hint, respectively.
Default value is \*(Aqno\*(Aq.
.RE
.sp
\fBreports.summary.tags\fP
.RS 4
Determines whether the tags column is shown in the summary.
Can be overridden by the \*(Aq:tags\*(Aq or \*(Aq:no\-tags\*(Aq hint, respectively.
Default value is \*(Aqyes\*(Aq.
.RE
.sp
\fBreports.summary.range\fP
.RS 4
Set the date range for the summary report.
The value has to correspond to a range hint, see timew\-hints(7).
Default value is \*(Aqday\*(Aq
.RE
.sp
\fBreports.summary.weekdays\fP
.RS 4
Determines whether the weekday column is shown in the summary.
Default value is \*(Aqyes\*(Aq
.RE
.sp
\fBreports.summary.weeks\fP
.RS 4
Determines whether the week column is shown in the summary.
Default value is \*(Aqyes\*(Aq
.RE
.sp
\fBtags.\fP\fI<tag>\fP\fB.color\fP
.RS 4
Assigns a specific foreground and background color to a tag.
Examples of valid colors include \*(Aqwhite\*(Aq, \*(Aqgray8\*(Aq, \*(Aqblack on yellow\*(Aq, and \*(Aqrgb345\*(Aq.
.RE
.SH "SEE ALSO"
.sp
\fBtimew\-day\fP(1),
\fBtimew\-hints\fP(7),
\fBtimew\-lengthen\fP(1),
\fBtimew\-modify\fP(1),
\fBtimew\-month\fP(1),
\fBtimew\-shorten\fP(1),
\fBtimew\-tag\fP(1),
\fBtimew\-untag\fP(1),
\fBtimew\-week\fP(1)