'\" t
.\"     Title: timew-config
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.13
.\"      Date: 2021-05-16
.\"    Manual: User Manuals
.\"    Source: timew 1.4.3
.\"  Language: English
.\"
.TH "TIMEW\-CONFIG" "1" "2021-05-16" "timew 1.4.3" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew-config \- get and set Timewarrior configuration
.SH "SYNOPSIS"
.sp
.nf
\fBtimew config\fP [\fI<name>\fP {\fI<value>\fP|\fB\(aq\(aq\fP}]
.fi
.br
.SH "DESCRIPTION"
.sp
Allows setting and removing configuration values, as an alternative to directly editing your ~/.timewarrior/timewarrior.cfg file.
.SH "EXAMPLES"
.sp
For example:
.sp
.if n .RS 4
.nf
.fam C
$ timew config verbose yes
$ timew config verbose \(aq\(aq
$ timew config verbose
.fam
.fi
.if n .RE
.sp
The first command sets \(aqverbose\(aq to \(aqyes\(aq.
The second sets it to a blank value which overrides the default value.
The third example deletes the \(aqverbose\(aq setting.
.sp
When modifying configuration in this way, interactive confirmation will be sought.
To override this confirmation, use the \(aq:yes\(aq hint, which means you intend to answer \(aqyes\(aq to the confirmation questions:
.sp
.if n .RS 4
.nf
.fam C
$ timew config verbose \(aq\(aq :yes
.fam
.fi
.if n .RE
.sp
If no arguments are provided, all configuration settings are shown:
.sp
.if n .RS 4
.nf
.fam C
$ timew config
verbose = yes
\&...
.fam
.fi
.if n .RE
.SH "SEE ALSO"
.sp
\fBtimew\-hints\fP(1),
\fBtimew\-show\fP(1)