'\" t
.\"     Title: timew-continue
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.13
.\"      Date: 2021-05-16
.\"    Manual: User Manuals
.\"    Source: timew 1.4.3
.\"  Language: English
.\"
.TH "TIMEW\-CONTINUE" "1" "2021-05-16" "timew 1.4.3" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew-continue \- resume tracking of existing interval
.SH "SYNOPSIS"
.sp
.nf
\fBtimew continue\fP [\fI<id>\fP|\fI<tag>\fP\fB...\fP] [\fI<datetime>\fP|\fI<range>\fP]
.fi
.br
.SH "DESCRIPTION"
.sp
The \(aqcontinue\(aq command is used to resume tracking specified by a closed interval.
This command is a convenient way to resume work without re\-entering the tags.
.sp
The interval to be resumed can be specified either by its id or by a set of tags.
Specifying multiple ids or both ids and tags will result in an error.
.sp
When given a set of tags, the first interval matching it will be taken as a blueprint for the new interval.
When given neither id nor tags, the first interval in the database is taken.
.sp
When no datetime or range given, the new interval is started at the current time.
.SH "EXAMPLES"
.sp
Using the \(aqsummary\(aq command and specifying the \(aq:ids\(aq hint shows interval IDs.
Consider the following intervals:
.sp
.if n .RS 4
.nf
.fam C
$ src/timew summary :ids
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
Wk  Date       Day ID Tags             Start      End    Time   Total
W23 2020\-06\-04 Thu @4 BAR           13:00:00 14:00:00 1:00:00
                   @3 BAR, FOO      14:00:00 15:00:00 1:00:00
                   @2 BAR, BAZ, FOO 15:00:00 16:00:00 1:00:00
                   @1 FOO           16:00:00 17:00:00 1:00:00 4:00:00
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
4:00:00
.fam
.fi
.if n .RE
.sp
Simple continue
.RS 4
.sp
.if n .RS 4
.nf
.fam C
$ timew continue
.fam
.fi
.if n .RE
.RE
.sp
The \(aqcontinue\(aq command creates a new open interval, starting now, with tag \(aqFOO\(aq
.sp
Continue an interval via id
.RS 4
.sp
.if n .RS 4
.nf
.fam C
$ timew continue @3
.fam
.fi
.if n .RE
.RE
.sp
The \(aqcontinue\(aq command creates a new open interval, starting now, with tags \(aqBAR\(aq and \(aqFOO\(aq.
.sp
Continue an interval via tag set
.RS 4
.sp
.if n .RS 4
.nf
.fam C
$ timew continue FOO BAR
.fam
.fi
.if n .RE
.RE
.sp
The \(aqcontinue\(aq command creates a new open interval, starting now, with tags \(aqFOO\(aq, \(aqBAR\(aq, and \(aqBAZ\(aq.
.sp
Note that the first matching interval (here \(aq@2\(aq) is taken as a blueprint for the new interval, although \(aq@3\(aq would have been a perfect match for the given tag set.
The command \(aqtimew continue BAR\(aq would have the same effect.
This means that there is no way to continue \(aq@4\(aq via a tag set.
.sp
Continue an interval at a specific date & time
.RS 4
.sp
.if n .RS 4
.nf
.fam C
$ timew continue @4 19:00  (1)
$ timew continue FOO 19:00 (2)
.fam
.fi
.if n .RE
.RE
.sp
The \(aqcontinue\(aq command creates a new open interval
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
with tag \(aqBAR\(aq (as specified by \(aq@4\(aq) and start time \(aq19:00\(aq.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
with tag \(aqFOO\(aq (as specified by \(aq@1\(aq) and start time \(aq19:00\(aq.
.sp
Continue an interval with a specific range
.RS 4
.sp
.if n .RS 4
.nf
.fam C
$ timew continue @4 19:00 \- 20:00  (1)
$ timew continue FOO 19:00 \- 20:00 (2)
.fam
.fi
.if n .RE
.RE
.RE
.sp
The \(aqcontinue\(aq command creates a new closed interval
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
with tag \(aqBAR\(aq (as specified by \(aq@4\(aq), start time \(aq19:00\(aq, and end time \(aq20:00\(aq.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
with tag \(aqFOO\(aq (as specified by \(aq@1\(aq) and start time \(aq19:00\(aq, and end time \(aq20:00\(aq.
.RE
.SH "SEE ALSO"
.sp
\fBtimew\-cancel\fP(1),
\fBtimew\-start\fP(1),
\fBtimew\-stop\fP(1),
\fBtimew\-track\fP(1)