'\" t
.\"     Title: timew-retag
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2023-10-14
.\"    Manual: User Manuals
.\"    Source: timew 1.7.0
.\"  Language: English
.\"
.TH "TIMEW\-RETAG" "1" "2023-10-14" "timew 1.7.0" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew-retag \- replace all tags in intervals
.SH "SYNOPSIS"
.sp
.nf
\fBtimew retag\fP [\fI<id>\fP\fB...\fP] \fI<tag>\fP\fB...\fP
.fi
.br
.SH "DESCRIPTION"
.sp
The \*(Aqretag\*(Aq command is used to replace all tags in an interval with the newly provided tags.
Using the \*(Aqsummary\*(Aq command, and specifying the \*(Aq:ids\*(Aq hint shows interval IDs.
Using the right ID, you can identify an interval to retag.
.SH "EXAMPLES"
.sp
For example, show the IDs:
.sp
.if n .RS 4
.nf
.fam C
$ timew summary :week :ids
.fam
.fi
.if n .RE
.sp
Then having selected \*(Aq@2\*(Aq as the interval you wish to retag:
.sp
.if n .RS 4
.nf
.fam C
$ timew retag @2 \*(AqNew Tag\*(Aq
.fam
.fi
.if n .RE
.sp
Note that you can retag multiple intervals, with multiple tags:
.sp
.if n .RS 4
.nf
.fam C
$ timew retag @2 @10 @23 \*(AqTag One\*(Aq tag2 tag3
.fam
.fi
.if n .RE
.sp
If there is active time tracking, you can omit the ID when you want to retag the current open interval:
.sp
.if n .RS 4
.nf
.fam C
$ timew start foo
$ timew retag bar
.fam
.fi
.if n .RE
.sp
This results in the current interval having only the \*(Aqbar\*(Aq tag.
.SH "SEE ALSO"
.sp
\fBtimew\-lengthen\fP(1),
\fBtimew\-shorten\fP(1),
\fBtimew\-summary\fP(1),
\fBtimew\-tag\fP(1),
\fBtimew\-untag\fP(1)