'\" t
.\"     Title: timew-move
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2023-10-14
.\"    Manual: User Manuals
.\"    Source: timew 1.7.0
.\"  Language: English
.\"
.TH "TIMEW\-MOVE" "1" "2023-10-14" "timew 1.7.0" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew-move \- change interval start\-time
.SH "SYNOPSIS"
.sp
.nf
\fBtimew move\fP \fI<id>\fP \fI<date>\fP
.fi
.br
.SH "DESCRIPTION"
.sp
The \*(Aqmove\*(Aq command is used to reposition an interval at a new start time.
Using the \*(Aqsummary\*(Aq command, and specifying the \*(Aq:ids\*(Aq hint shows interval IDs.
Using the right ID, you can identify an interval to move.
.SH "EXAMPLES"
.sp
For example, show the IDs:
.sp
.if n .RS 4
.nf
.fam C
$ timew summary :week :ids
.fam
.fi
.if n .RE
.sp
Then having selected \*(Aq@2\*(Aq as the interval you wish to move:
.sp
.if n .RS 4
.nf
.fam C
$ timew move @2 9am
.fam
.fi
.if n .RE
.SH "SEE ALSO"
.sp
\fBtimew\-lengthen\fP(1),
\fBtimew\-modify\fP(1),
\fBtimew\-resize\fP(1),
\fBtimew\-shorten\fP(1),
\fBtimew\-summary\fP(1),
\fBtimew\-tag\fP(1),
\fBtimew\-untag\fP(1)