'\" t
.\"     Title: timew-config
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2023-10-14
.\"    Manual: User Manuals
.\"    Source: timew 1.7.0
.\"  Language: English
.\"
.TH "TIMEW\-CONFIG" "1" "2023-10-14" "timew 1.7.0" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew-config \- get and set Timewarrior configuration
.SH "SYNOPSIS"
.sp
.nf
\fBtimew config\fP [\fI<name>\fP {\fI<value>\fP|\fB\*(Aq\*(Aq\fP}]
.fi
.br
.SH "DESCRIPTION"
.sp
Allows setting and removing configuration values, as an alternative to directly editing your \fItimewarrior.cfg\fP file.
.SH "EXAMPLES"
.sp
For example:
.sp
.if n .RS 4
.nf
.fam C
$ timew config verbose yes
$ timew config verbose \*(Aq\*(Aq
$ timew config verbose
.fam
.fi
.if n .RE
.sp
The first command sets \*(Aqverbose\*(Aq to \*(Aqyes\*(Aq.
The second sets it to a blank value which overrides the default value.
The third example deletes the \*(Aqverbose\*(Aq setting.
.sp
When modifying configuration in this way, interactive confirmation will be sought.
To override this confirmation, use the \*(Aq:yes\*(Aq hint, which means you intend to answer \*(Aqyes\*(Aq to the confirmation questions:
.sp
.if n .RS 4
.nf
.fam C
$ timew config verbose \*(Aq\*(Aq :yes
.fam
.fi
.if n .RE
.sp
If no arguments are provided, all configuration settings are shown:
.sp
.if n .RS 4
.nf
.fam C
$ timew config
verbose = yes
\&...
.fam
.fi
.if n .RE
.SH "SEE ALSO"
.sp
\fBtimew\-hints\fP(1),
\fBtimew\-show\fP(1)