.TH timew-extensions 1 "2020-05-04" "timew 1.3.0" "User Manuals"
.
.SH NAME
timew-extensions \- list available extensions
.
.SH SYNOPSIS
.B timew extensions
.
.SH DESCRIPTION
Displays the directory containing the extension programs and a table showing each extension and its status.
.
.SH "SEE ALSO"
.BR timew-diagnostics (1)
