'\" t
.\"     Title: timew-report
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2023-10-14
.\"    Manual: User Manuals
.\"    Source: timew 1.7.0
.\"  Language: English
.\"
.TH "TIMEW\-REPORT" "1" "2023-10-14" "timew 1.7.0" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew-report \- run an extension report
.SH "SYNOPSIS"
.sp
.nf
\fBtimew\fP [\fBreport\fP] \fI<report>\fP [\fI<range>\fP] [\fI<tag>\fP\fB...\fP]
.fi
.br
.SH "DESCRIPTION"
.sp
Runs an extension report, and supports filtering data.
The \*(Aqreport\*(Aq command itself is optional, which means that these two commands are equivalent:
.sp
.if n .RS 4
.nf
.fam C
$ timew report foo :week
$ timew        foo :week
.fam
.fi
.if n .RE
.sp
This does however assume there is a \*(Aqfoo\*(Aq extension installed.
.sp
The return code is the return code of the extension.
If the extension produces no output and a non\-zero rc, then 255 is returned.
.SH "CONFIGURATION"
.sp
\fBreports.range\fP
.RS 4
Sets the default date range for all reports.
The value has to correspond to a range hint, see timew\-hints(7).
Defaults to \f(CRall\fP
.RE
.sp
\fBreports.\fP\fI<name>\fP\fB.range\fP
.RS 4
Set the date range for report \fIname\fP, used if no \fIrange\fP is given on the command line.
Here, \fIname\fP is the name of the report executable without its extension (i.e. a report executable \*(Aqfoo.py\*(Aq is referred to by \*(Aqfoo\*(Aq).
The value has to correspond to a range hint, see timew\-hints(7).
.RE