'\" t
.\"     Title: timew
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.13
.\"      Date: 2021-05-16
.\"    Manual: User Manuals
.\"    Source: timew 1.4.3
.\"  Language: English
.\"
.TH "TIMEW" "1" "2021-05-16" "timew 1.4.3" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew \- a command line time tracker
.SH "SYNOPSIS"
.sp
.nf
\fBtimew\fP [\fB\-\-version\fP|\fB\-\-help\fP]
\fBtimew\fP [\fI<command>\fP [\fI<arg>\fP\fB...\fP]]
.fi
.br
.SH "DESCRIPTION"
.sp
Timewarrior is a command line time tracker.
It allows you to easily track your time and generate summary reports.
.sp
This is a reference, not a tutorial.
If you are looking for a tutorial, check the online documentation here:
.sp
.if n .RS 4
.nf
.fam C
https://timewarrior.net/docs/
.fam
.fi
.if n .RE
.sp
When run without arguments or options, the default command is run, which indicates whether there is any active tracking, and if so, shows a summary, then exits with a code 0.
If there is no active time tracking, exit code is 1.
.SH "OPTIONS"
.sp
\fB\-\-version\fP
.RS 4
Displays Timewarrior version information
.RE
.sp
\fB\-\-help\fP
.RS 4
Displays Timewarrior usage information
.RE
.SH "TIMEWARRIOR COMMANDS"
.sp
Timewarrior supports many commands.
Alphabetically:
.sp
\fBtimew\-annotate\fP(1)
.RS 4
Add annotation to intervals
.RE
.sp
\fBtimew\-cancel\fP(1)
.RS 4
Cancel time tracking
.RE
.sp
\fBtimew\-config\fP(1)
.RS 4
Get and set Timewarrior configuration
.RE
.sp
\fBtimew\-continue\fP(1)
.RS 4
Resume tracking of existing interval
.RE
.sp
\fBtimew\-day\fP(1)
.RS 4
Display day chart
.RE
.sp
\fBtimew\-delete\fP(1)
.RS 4
Delete intervals
.RE
.sp
\fBtimew\-diagnostics\fP(1)
.RS 4
Show diagnostic information
.RE
.sp
\fBtimew\-export\fP(1)
.RS 4
Export tracked time in JSON
.RE
.sp
\fBtimew\-extensions\fP(1)
.RS 4
List available extensions
.RE
.sp
\fBtimew\-get\fP(1)
.RS 4
Display DOM values
.RE
.sp
\fBtimew\-help\fP(1)
.RS 4
Display help
.RE
.sp
\fBtimew\-join\fP(1)
.RS 4
Join intervals
.RE
.sp
\fBtimew\-lengthen\fP(1)
.RS 4
Lengthen intervals
.RE
.sp
\fBtimew\-modify\fP(1)
.RS 4
Change start or end time of an interval
.RE
.sp
\fBtimew\-month\fP(1)
.RS 4
Display month chart
.RE
.sp
\fBtimew\-move\fP(1)
.RS 4
Change interval start\-time
.RE
.sp
\fBtimew\-report\fP(1)
.RS 4
Run an extension report
.RE
.sp
\fBtimew\-resize\fP(1)
.RS 4
Set interval duration
.RE
.sp
\fBtimew\-shorten\fP(1)
.RS 4
Shorten intervals
.RE
.sp
\fBtimew\-show\fP(1)
.RS 4
Display configuration
.RE
.sp
\fBtimew\-split\fP(1)
.RS 4
Split intervals
.RE
.sp
\fBtimew\-start\fP(1)
.RS 4
Start time tracking
.RE
.sp
\fBtimew\-stop\fP(1)
.RS 4
Stop time tracking
.RE
.sp
\fBtimew\-summary\fP(1)
.RS 4
Display a time\-tracking summary
.RE
.sp
\fBtimew\-tag\fP(1)
.RS 4
Add tags to intervals
.RE
.sp
\fBtimew\-tags\fP(1)
.RS 4
Display a list of tags
.RE
.sp
\fBtimew\-track\fP(1)
.RS 4
Add intervals to the database
.RE
.sp
\fBtimew\-undo\fP(1)
.RS 4
Undo Timewarrior commands
.RE
.sp
\fBtimew\-untag\fP(1)
.RS 4
Remove tags from intervals
.RE
.sp
\fBtimew\-week\fP(1)
.RS 4
Display week chart
.RE
.SH "MORE EXAMPLES"
.sp
For examples please see the online documentation starting at:
.sp
.URL "https://timewarrior.net/docs/" "" ""
.sp
Note that the online documentation can be more detailed and more current than this man page
.SH "FILES"
.sp
~/.timewarrior/timewarrior.cfg
.RS 4
User configuration file.
.RE
.sp
~/.timewarrior/data/YYYY\-MM.data
.RS 4
Time tracking data files.
.RE
.SH "CREDITS & COPYRIGHT"
.sp
Copyright \(co 2015 \- 2018 T. Lauf, P. Beckingham, F. Hernandez.
.br
Timewarrior is distributed under the MIT license.
See \c
.URL "https://www.opensource.org/licenses/mit\-license.php" "" ""
for more information.
.SH "FURTHER DOCUMENTATION"
.sp
For more information regarding Timewarrior, see the following:
.sp
The official site at \c
.URL "https://timewarrior.net" "" ""
.sp
The official code repository at \c
.URL "https://github.com/GothenburgBitFactory/timewarrior" "" ""
.sp
You can contact the project by emailing \c
.MTO "support\(atgothenburgbitfactory.org" "" ""
.SH "REPORTING BUGS"
.sp
Bugs in Timewarrior may be reported to the issue\-tracker at \c
.URL "https://github.com/GothenburgBitFactory/timewarrior/issues" "" ""
.SH "SEE ALSO"
.sp
\fBtimew\-config\fP(7),
\fBtimew\-dates\fP(7),
\fBtimew\-dom\fP(7),
\fBtimew\-durations\fP(7),
\fBtimew\-hints\fP(7),
\fBtimew\-range\fP(7)