'\" t
.\"     Title: timew-untag
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.13
.\"      Date: 2021-05-16
.\"    Manual: User Manuals
.\"    Source: timew 1.4.3
.\"  Language: English
.\"
.TH "TIMEW\-UNTAG" "1" "2021-05-16" "timew 1.4.3" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew-untag \- remove tags from intervals
.SH "SYNOPSIS"
.sp
.nf
\fBtimew untag\fP [\fI<id>\fP\fB...\fP ] \fI<tag>\fP\fB...\fP
.fi
.br
.SH "DESCRIPTION"
.sp
The \(aquntag\(aq command is used to remove a tag from an interval.
Using the \(aqsummary\(aq command, and specifying the \(aq:ids\(aq hint shows interval IDs.
Using the right ID, you can identify an interval to untag.
.SH "EXAMPLES"
.sp
For example, show the IDs:
.sp
.if n .RS 4
.nf
.fam C
$ timew summary :week :ids
.fam
.fi
.if n .RE
.sp
Then having selected \(aq@2\(aq as the interval you wish to untag:
.sp
.if n .RS 4
.nf
.fam C
$ timew untag @2 \(aqOld Tag\(aq
.fam
.fi
.if n .RE
.sp
Note that you can untag multiple intervals, with multiple tags:
.sp
.if n .RS 4
.nf
.fam C
$ timew untag @2 @10 @23 \(aqOld Tag\(aq tag2 tag3
.fam
.fi
.if n .RE
.sp
If there is active time tracking, you can omit the ID when you want to remove tags from the current open interval:
.sp
.if n .RS 4
.nf
.fam C
$ timew start foo bar
$ timew untag bar
.fam
.fi
.if n .RE
.sp
This results in the current interval having tag \(aqfoo\(aq but not \(aqbar\(aq.
.SH "SEE ALSO"
.sp
\fBtimew\-lengthen\fP(1),
\fBtimew\-shorten\fP(1),
\fBtimew\-summary\fP(1),
\fBtimew\-tag\fP(1)