'\" t
.\"     Title: timew-ranges
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.13
.\"      Date: 2021-05-16
.\"    Manual: User Manuals
.\"    Source: timew 1.4.3
.\"  Language: English
.\"
.TH "TIMEW\-RANGES" "7" "2021-05-16" "timew 1.4.3" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE pass:[blue\ R\ <\ >]
.\}
.SH "NAME"
timew-ranges \- date and time ranges supported by Timewarrior
.SH "SYNOPSIS"

.SH "DESCRIPTION"
.sp
An interval defines a block of time that is tracked.
The syntax for specifying an interval is flexible, and may be one of:
.sp
.if n .RS 4
.nf
.fam C
[from] <date>
[from] <date> to/\- <date>
[from] <date> for <duration>
<duration> before/after <date>
<duration> ago
[for] <duration>
.fam
.fi
.if n .RE
.sp
Examples are:
.sp
.if n .RS 4
.nf
.fam C
from 9:00
from 9am \- 11am
from 9:00:00 to 11:00
from 9:00 for 2h
2h after 9am
2h before 11:00
2h ago
for 2h
.fam
.fi
.if n .RE
.sp
An interval is said to be \(aqclosed\(aq if there is both a start and end, and \(aqopen\(aq if there is no end date.