name: timewarrior
base: core22
version: '1.1.0'
summary: Tracks time from the command line.
description: |
  Timewarrior is a time tracking utility that offers simple stopwatch features as well as sophisticated calendar-based backfill, along with flexible reporting. It is a portable, well-supported and very active Open Source project.

#grade: devel           # This is for development only.
#confinement: devmode   # This is for development only. Unconfined snap environment. For production, use strict.
grade: stable           # This is for releasing in the stable channel.
confinement: strict     # This is for production only.

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]
  - build-on: [amd64, armhf]
    build-for: [armhf]
  - build-on: [amd64, ppc64el]
    build-for: [ppc64el]
  - build-on: [amd64, s390x]
    build-for: [s390x]

apps:
  timewarrior:
    command: usr/bin/timew
    plugs: [home, network]

parts:
  timewarrior:
    plugin: cmake
    source: source
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    stage-packages:
      - libc6
